general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = pidof hyprlock || hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 600                                                                                               # 10 minutes
    on-timeout = hyprctl dispatch dpms off                                                                      # turn off displays
    on-resume = hyprctl dispatch dpms on                                                                        # turn displays back on
}

listener {
    timeout = 7200                                                                                              # 2 hours (120 minutes)
    on-timeout = systemctl suspend                                                                              # put system to sleep
}

listener {
    timeout = 180                                                                                               # 3 minutes
    on-timeout = sh -c 'loginctl show-session self -p LockedHint --value | grep -q yes && systemctl suspend'    # suspend quickly if locked
}
